# Generated by Django 3.1.2 on 2020-12-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContingentWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conName', models.CharField(max_length=255)),
                ('WorkStart', models.DateField()),
                ('workEnd', models.DateField()),
                ('FTE', models.DecimalField(decimal_places=2, max_digits=2)),
                ('workSchedule', models.CharField(max_length=255)),
                ('payRate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('CustAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustAddress', to='company.address')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('SSN', models.CharField(max_length=255)),
                ('addID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addID', to='company.address')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invDate', models.DateField(auto_now_add=True)),
                ('saleType', models.CharField(max_length=255)),
                ('fulfillmentDate', models.DateField()),
                ('DatePaid', models.DateField()),
                ('InvoiceStatus', models.CharField(max_length=255)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LastUpdated', models.DateField()),
                ('payingCust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payingCust', to='company.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('inventoryRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itemValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saleRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('VolumeReq', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineItemType', models.CharField(max_length=255)),
                ('dateRequested', models.DateField()),
                ('lineItemStatus', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemID', to='company.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillmentStart', models.DateTimeField()),
                ('Action', models.CharField(max_length=255)),
                ('fulfillmentEnd', models.DateTimeField()),
                ('amountMoved', models.PositiveIntegerField()),
                ('refEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refEmp', to='company.employee')),
                ('refLineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refLineItem', to='company.lineitem')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posName', models.CharField(max_length=255)),
                ('FTE', models.DecimalField(decimal_places=2, max_digits=2)),
                ('workSchedule', models.CharField(max_length=255)),
                ('payRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empRef', to='company.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xLoc', models.PositiveIntegerField()),
                ('yLoc', models.PositiveIntegerField()),
                ('zLoc', models.PositiveIntegerField()),
                ('shelfCapacity', models.PositiveIntegerField()),
                ('StorageType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whName', models.CharField(max_length=255)),
                ('regularFTE', models.PositiveIntegerField()),
                ('TotalFTE', models.PositiveIntegerField()),
                ('shelfXYZ', models.PositiveIntegerField()),
                ('whAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whAddress', to='company.address')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DisposalRate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='WhEmploymentTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whTemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whTemp', to='company.contingentworker')),
                ('whWareTemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whWareTemp', to='company.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WhEmploymentPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whPos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whPos', to='company.position')),
                ('whWare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whWare', to='company.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=255)),
                ('dateOpened', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='company.address')),
                ('refCust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refCust', to='company.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShelfMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amtMoved', models.PositiveIntegerField()),
                ('actionRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionRef', to='company.orderaction')),
                ('shelfRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelfRef', to='company.shelf')),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='whLoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whLoc', to='company.warehouse'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus', models.CharField(max_length=255)),
                ('DateRequested', models.DateField()),
                ('invRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invRef', to='company.invoice')),
                ('orderingCust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderingCust', to='company.customer')),
            ],
        ),
        migrations.AddField(
            model_name='orderaction',
            name='refShelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refShelf', to='company.shelf'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='ordRefMain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordRefMain', to='company.orders'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='shippingLoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingLoc', to='company.address'),
        ),
        migrations.CreateModel(
            name='FulfillmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeAssigned', models.DateTimeField()),
                ('timeFulfilled', models.DateTimeField()),
                ('mgrRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mgrRef', to='company.employee')),
                ('ordRefFul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordRefFul', to='company.orders')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='warCust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warCust', to='company.warehousecustomer'),
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='ContEmpRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContEmpRef', to='company.employee'),
        ),
    ]
