# Generated by Django 3.1.2 on 2020-12-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='DatePaid',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fulfillmentDate',
            field=models.DateField(null=True),
        ),
    ]
