# Generated by Django 3.1.2 on 2020-12-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201212_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='LastUpdated',
            field=models.DateField(null=True),
        ),
    ]
