# Generated by Django 3.1.2 on 2020-12-15 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_shelf_capacityused'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='refWHouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refWHouse', to='company.warehouse'),
        ),
        migrations.AddField(
            model_name='orderaction',
            name='batchNumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderaction',
            name='amountMoved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderaction',
            name='fulfillmentStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderaction',
            name='refShelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refShelf', to='company.shelf'),
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amtOrd', models.PositiveIntegerField()),
                ('strOrdSts', models.CharField(max_length=255)),
                ('endCust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endCust', to='company.customer')),
                ('itemOrd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemOrd', to='company.item')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('refItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refItem', to='company.item')),
                ('refStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refStore', to='company.store')),
            ],
        ),
    ]
