# Generated by Django 3.1.2 on 2020-12-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20201214_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='storedItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storedItem', to='company.item'),
        ),
    ]
