# Generated by Django 3.1.2 on 2020-12-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_shelf_storeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
