# Generated by Django 3.1.2 on 2020-12-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201214_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whemploymenttemp',
            name='whTemp',
        ),
        migrations.RemoveField(
            model_name='whemploymenttemp',
            name='whWareTemp',
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='whCon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whCon', to='company.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='whPos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whPos', to='company.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contingentworker',
            name='ContEmpRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContEmpRef', to='company.employee'),
        ),
        migrations.AlterField(
            model_name='position',
            name='empRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empRef', to='company.employee'),
        ),
        migrations.DeleteModel(
            name='WhEmploymentPerm',
        ),
        migrations.DeleteModel(
            name='WhEmploymentTemp',
        ),
    ]
