# Generated by Django 3.1.2 on 2020-12-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20201215_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaction',
            name='fulfillmentEnd',
            field=models.DateTimeField(default='2100-01-01'),
        ),
    ]
