# Generated by Django 3.1.2 on 2020-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20201215_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingentworker',
            name='FTE',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='position',
            name='FTE',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
