# Generated by Django 3.1.2 on 2020-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20201215_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
